node_number: 1
node_port: 8081
owned_files_dir: "Node1/ownedFiles/"
new_files_dir: "Node1/newFiles/"
owned_files:
  - "file1"
friend_nodes:
  - node_name: 2
    node_port: 8082
  - node_name: 5
    node_port: 8085
  - node_name: 6
    node_port: 8086
