node_number: 5
node_port: 8085
owned_files_dir: "Node5/ownedFiles/"
new_files_dir: "Node5/newFiles/"
owned_files:
  - "file5"
friend_nodes:
  - node_name: 1
    node_port: 8081
  - node_name: 2
    node_port: 8082
  - node_name: 3
    node_port: 8083
  - node_name: 4
    node_port: 8084
  - node_name: 7
    node_port: 8087
  - node_name: 8
    node_port: 8088
