node_number: 8
node_port: 8088
owned_files_dir: "Node8/ownedFiles/"
new_files_dir: "Node8/newFiles/"
owned_files:
  - "file8"
friend_nodes:
  - node_name: 2
    node_port: 8082
  - node_name: 4
    node_port: 8084
  - node_name: 5
    node_port: 8085
  - node_name: 7
    node_port: 8087
    
