node_number: 7
node_port: 8087
owned_files_dir: "Node7/ownedFiles/"
new_files_dir: "Node7/newFiles/"
owned_files:
  - "file7"
friend_nodes:
  - node_name: 5
    node_port: 8085
  - node_name: 8
    node_port: 8088
