node_files:
  - node_name: 1
    node_files:
      - "file1"
  - node_name: 2
    node_files:
      - "file2"
  - node_name: 3
    node_files:
      - "file3"
  - node_name: 4
    node_files:
      - "file4"
  - node_name: 5
    node_files:
      - "file5"
  - node_name: 6
    node_files:
      - "file6"
  - node_name: 7
    node_files:
      - "file7"
  - node_name: 8
    node_files:
      - "file8"
